VERSION 0.7

FROM node:latest

WORKDIR /app

deps:
    COPY package.json package-lock.json ./
    RUN npm install
    COPY tsconfig.json svelte.config.js vite.config.ts ./
    COPY src src
    COPY static static
    SAVE IMAGE --cache-hint

build:
    FROM +deps
    RUN npm run check && \
        npm run lint && \
        npm run build
    SAVE ARTIFACT build
    SAVE IMAGE --cache-hint
