VERSION 0.7

FROM node:latest

deps:
    COPY package.json package-lock.json ./
    RUN npm install
    COPY tsconfig.json svelte.config.js vite.config.ts ./
    COPY src src
    COPY static static

build:
    FROM +deps
    RUN npm run build
    SAVE ARTIFACT build /build AS LOCAL build
