# Test your FastAPI endpoints

GET {{base_url}}
Accept: application/json

###

GET {{base_url}}/_/healthy
Accept: application/json

###

GET {{base_url}}/_/ready
Accept: application/json

###

GET {{base_url}}/api/v1/quotes/
Accept: application/json

###

GET {{base_url}}/api/v1/quotes/1
Accept: application/json

###
