strictness: high
test-warnings: true
doc-warnings: false
max-line-length: 120

ignore-paths:
  - build
  - .git
  - __pycache__
  - .eggs
  - dist
  - .tox
  - .cachedocs
  - quotes/api/deps.py

pep8:
  disable:
    - N805

mccabe:
  max-complexity: 10

pylint:
  run: false

pyroma:
  run: false

frosted:
  run: false

vulture:
  run: false

pep257:
  run: false
