VERSION 0.8

IMPORT github.com/mortenlj/earthly-lib/kubernetes/commands AS lib-k8s-commands

FROM busybox

INSTALL_MISE:
    FUNCTION
    ENV MISE_DATA_DIR="/mise"
    ENV MISE_CONFIG_DIR="/mise"
    ENV MISE_CACHE_DIR="/mise/cache"
    ENV MISE_INSTALL_PATH="/usr/local/bin/mise"
    ENV PATH="/mise/shims:$PATH"

    COPY mise.toml .
    RUN curl https://mise.run | sh && \
        mise trust /app/mise.toml

deps:
    FROM python:3.11

    WORKDIR /app

    DO +INSTALL_MISE
    RUN mise install uv

    COPY pyproject.toml uv.lock .
    RUN uv sync --no-install-workspace --locked --compile-bytecode

    SAVE ARTIFACT .venv
    SAVE IMAGE --cache-hint


build:
    FROM +deps

    RUN uv sync --locked --compile-bytecode --group=dev

    COPY --dir .prospector.yaml quotes .
    RUN uv run black --check . && \
        uv run prospector

    SAVE ARTIFACT quotes
    SAVE IMAGE --cache-hint

test:
    LOCALLY
    RUN uv sync --locked --compile-bytecode && \
        uv run black --check . && \
        uv run prospector

black:
    LOCALLY
    RUN uv sync --locked --compile-bytecode && \
        uv run black --check .
