name: quotes

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: mortenlj/mise-lib/.github/workflows/setup.yaml@main

  build:
    permissions:
      packages: write
      checks: write
      pull-requests: write
    needs: setup
    uses: mortenlj/mise-lib/.github/workflows/build-docker.yaml@main
    with:
      main-image: ghcr.io/${{ github.repository }}
      clean-version: ${{ fromJSON(needs.setup.outputs.clean-version) }}
      tool-versions: ${{ needs.setup.outputs.tool-versions }}
    secrets:
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
    needs:
      - setup
      - build
    uses: mortenlj/mise-lib/.github/workflows/deploy.yaml@main
    secrets:
      ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
      ZEROTIER_API_ACCESSTOKEN: ${{ secrets.ZEROTIER_API_ACCESSTOKEN }}

  cleanup:
    permissions:
      packages: write
    needs: build
    uses: mortenlj/mise-lib/.github/workflows/cleanup.yaml@main
